name: Test Outrunner

on:
  workflow_dispatch:
    inputs:
      label:
        description: "runs-on label"
        required: true
        default: "linux-arm64"

jobs:
  smoke:
    runs-on: ${{ inputs.label }}
    steps:
      - run: echo "Hello from outrunner!"
      - run: uname -a
